channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - autodocsumm
  - biopython
  - cython
  - lxml
  - matplotlib
  - matplotlib-venn
  - notebook
  - numpy
  - pandas
  - pyranges
  - pysam
  - scipy
  - seaborn
  - sphinx-issues
  - sphinx_rtd_theme
  - twine
