channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - autodocsumm
  - cython
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pyranges
  - seaborn
  - sphinx-issues
  - sphinx_rtd_theme
  - twine
